name: Sorpresa
description: Una pequeña sorpresa para ti <3.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.15.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/images/launcher/icon.png"


flutter:

  uses-material-design: true
  assets:
   - assets/images/back.jpg
   - assets/images/left.png
   - assets/images/right.png
   - assets/images/top.png
   - assets/images/bottom.png
   - assets/images/center.png
   - assets/images/a.png
   - assets/images/b.png
   - assets/images/x.png
   - assets/images/y.png
   - assets/images/heart.png
   - assets/images/launcher/game_icon.png
   - assets/images/messages/message_00.png
   - assets/images/messages/message_01.png
   - assets/images/messages/message_02.png
   - assets/images/messages/message_03.png
   - assets/images/messages/message_04.png
   - assets/images/messages/message_05.png
   - assets/images/messages/message_06.png
   - assets/images/omar_walking_left/tile000.png
   - assets/images/omar_walking_left/tile001.png
   - assets/images/omar_walking_left/tile002.png
   - assets/images/omar_walking_left/tile003.png
   - assets/images/omar_walking_left/tile004.png
   - assets/images/omar_walking_left/tile005.png
   - assets/images/omar_walking_left/tile006.png
   - assets/images/omar_walking_left/tile007.png
   - assets/images/omar_walking_right/tile000.png
   - assets/images/omar_walking_right/tile001.png
   - assets/images/omar_walking_right/tile002.png
   - assets/images/omar_walking_right/tile003.png
   - assets/images/omar_walking_right/tile004.png
   - assets/images/omar_walking_right/tile005.png
   - assets/images/omar_walking_right/tile006.png
   - assets/images/omar_walking_right/tile007.png
   - assets/images/omar_walking_top/tile000.png
   - assets/images/omar_walking_top/tile001.png
   - assets/images/omar_walking_top/tile002.png
   - assets/images/omar_walking_top/tile003.png
   - assets/images/omar_walking_top/tile004.png
   - assets/images/omar_walking_top/tile005.png
   - assets/images/omar_walking_top/tile006.png
   - assets/images/omar_walking_top/tile007.png
   - assets/images/omar_walking_bottom/tile000.png
   - assets/images/omar_walking_bottom/tile001.png
   - assets/images/omar_walking_bottom/tile002.png
   - assets/images/omar_walking_bottom/tile003.png
   - assets/images/omar_walking_bottom/tile004.png
   - assets/images/omar_walking_bottom/tile005.png
   - assets/images/omar_walking_bottom/tile006.png
   - assets/images/omar_walking_bottom/tile007.png
   - assets/images/eloir_walking_left/tile000.png
   - assets/images/eloir_walking_left/tile001.png
   - assets/images/eloir_walking_left/tile002.png
   - assets/images/eloir_walking_left/tile003.png
   - assets/images/eloir_walking_left/tile004.png
   - assets/images/eloir_walking_left/tile005.png
   - assets/images/eloir_walking_left/tile006.png
   - assets/images/eloir_walking_left/tile007.png
   - assets/images/eloir_walking_bottom/tile000.png
   - assets/images/eloir_walking_bottom/tile001.png
   - assets/images/eloir_walking_bottom/tile002.png
   - assets/images/eloir_walking_bottom/tile003.png
   - assets/images/eloir_walking_bottom/tile004.png
   - assets/images/eloir_walking_bottom/tile005.png
   - assets/images/eloir_walking_bottom/tile006.png
   - assets/images/eloir_walking_bottom/tile007.png
   - assets/images/eloir_walking_right/tile000.png
   - assets/images/eloir_walking_right/tile001.png
   - assets/images/eloir_walking_right/tile002.png
   - assets/images/eloir_walking_right/tile003.png
   - assets/images/eloir_walking_right/tile004.png
   - assets/images/eloir_walking_right/tile005.png
   - assets/images/eloir_walking_right/tile006.png
   - assets/images/eloir_walking_right/tile007.png
   - assets/images/eloir_walking_top/tile000.png
   - assets/images/eloir_walking_top/tile001.png
   - assets/images/eloir_walking_top/tile002.png
   - assets/images/eloir_walking_top/tile003.png
   - assets/images/eloir_walking_top/tile004.png
   - assets/images/eloir_walking_top/tile005.png
   - assets/images/eloir_walking_top/tile006.png
   - assets/images/eloir_walking_top/tile007.png